
obj-y += giant-misc.o giant-pm.o

obj-$(CONFIG_FB_JZ4780_LCDC0)     += giant-lcd.o
obj-$(CONFIG_FB_JZ4780_LCDC1)     += giant-lcd.o
obj-$(CONFIG_MMC_JZ4780)	+= giant-mmc.o
obj-$(CONFIG_JZ4780_INTERNAL_CODEC) += giant-sound.o
obj-$(CONFIG_NAND_JZ4780)	+= giant-nand.o
