# Makefile for the xburst sound oss driver
#
# 24 APR 2012, <jbbi: jbbi@ingernic.cn>
#

obj-$(CONFIG_SOUND_I2S0_JZ47XX) 	+= codecs/

obj-$(CONFIG_SOUND_I2S0_JZ47XX) 	+= xb47xx_i2s0.o

obj-$(CONFIG_SOUND_I2S1_JZ47XX) 	+= xb47xx_i2s1.o

obj-$(CONFIG_SOUND_PCM0_JZ47XX) 	+= xb47xx_pcm0.o

obj-$(CONFIG_SOUND_PCM1_JZ47XX) 	+= xb47xx_pcm1.o