# Makefile for nand block
#

EXTRA_CFLAGS	+= -Idrivers/nand/manager/inc/ \
		-Idrivers/nand/inc/ \
		-Idrivers/nand/manager/inc/linux/

obj-y		+= manager/ nand_block.o nand_char.o nand_debug.o
obj-y		+= driver/
