
snd-asoc-dma-objs := asoc-dma.o
snd-asoc-aic-objs := asoc-aic.o
snd-asoc-i2s-objs := asoc-i2s.o
snd-asoc-pcm-objs := asoc-pcm.o
snd-asoc-spdif-objs := asoc-spdif.o

snd-asoc-icdc-d1-objs := icodec/icdc_d1.o
snd-asoc-icdc-d2-objs := icodec/icdc_d2.o
snd-asoc-pcm-dump-objs := icodec/pcm_dump.o
snd-asoc-spdif-dump-objs := icodec/spdif_dump.o

obj-$(CONFIG_SND_ASOC_INGENIC) += snd-asoc-dma.o
obj-$(CONFIG_SND_ASOC_JZ_AIC) += snd-asoc-aic.o
obj-$(CONFIG_SND_ASOC_JZ_AIC_I2S) += snd-asoc-i2s.o
obj-$(CONFIG_SND_ASOC_JZ_ICDC_D1) += snd-asoc-icdc-d1.o
obj-$(CONFIG_SND_ASOC_JZ_ICDC_D2) += snd-asoc-icdc-d2.o
obj-$(CONFIG_SND_ASOC_JZ_PCM) += snd-asoc-pcm.o
obj-$(CONFIG_SND_ASOC_JZ_PCM_DUMP_CDC) += snd-asoc-pcm-dump.o

obj-$(CONFIG_SND_ASOC_JZ_SPDIF) += snd-asoc-spdif.o
obj-$(CONFIG_SND_ASOC_JZ_SPDIF_DUMP_CDC) += snd-asoc-spdif-dump.o

snd-soc-dorado-icdc-objs := dorado_icdc.o
snd-soc-mensa-icdc-objs := mensa_icdc.o
snd-soc-mensa-spdif-objs := mensa_spdif.o
obj-$(CONFIG_SND_ASOC_INGENIC_DORADO_ICDC) += snd-soc-dorado-icdc.o
obj-$(CONFIG_SND_ASOC_INGENIC_MENSA_ICDC) += snd-soc-mensa-icdc.o
obj-$(CONFIG_SND_ASOC_INGENIC_MENSA_SPDIF) += snd-soc-mensa-spdif.o
