
snd-asoc-dma-objs := asoc-dma.o
snd-asoc-aic-objs := asoc-aic.o
snd-asoc-i2s-objs := asoc-i2s.o
snd-asoc-dlv4780-objs := icodec/dlv4780.o

obj-$(CONFIG_SND_ASOC_INGENIC) += snd-asoc-dma.o
obj-$(CONFIG_SND_ASOC_JZ_AIC) += snd-asoc-aic.o
obj-$(CONFIG_SND_ASOC_JZ_AIC_I2S) += snd-asoc-i2s.o
obj-$(CONFIG_SND_ASOC_JZ_DLV4780) += snd-asoc-dlv4780.o

snd-soc-dorado-dlv4780-objs := dorado_dlv4780.o
obj-$(CONFIG_SND_ASOC_INGENIC_DORADO_DLV4780) += snd-soc-dorado-dlv4780.o
