
obj-$(CONFIG_JZ_CIM)		+= jz_cim.o
obj-$(CONFIG_OV2650)		+= ov2650/
obj-$(CONFIG_OV7675)		+= ov7675/
obj-$(CONFIG_OV2659_MODULE)		+= ov2659/
obj-$(CONFIG_SP0838)		+= sp0838/
obj-$(CONFIG_FAKE)		+= fake/
