#KERNELDIR = /home1/hyli/android-4775/kernel
#OUTFILE = /home1/hyli/android-4775/kernel/drivers/video/jz4780-fb/lcd_suspend_update/customer_moduel_suspend_update_display
ccflags-m += -Idrivers/video/jz4780-fb/lcd_suspend_update/
obj-m += wakeup_and_update_display.o
#all:
#	make -C $(KERNELDIR) M=$(OUTFILE) modules
#clean:
#	rm *.ko *mod* *order
