
obj-y += captain-misc.o captain-pm.o captain-lcd.o  

obj-$(CONFIG_I2C)		+= captain-i2c.o
obj-$(CONFIG_MFD_ACT8600)	+= captain-regulator.o
obj-$(CONFIG_MMC_JZ4780)	+= captain-mmc.o
obj-$(CONFIG_JZ4780_INTERNAL_CODEC) += captain-sound.o
obj-$(CONFIG_NAND_JZ4780)	+= captain-nand.o
