# drivers/nand/driver/Makefile 
#

#KBUILD_CFLAGS += -I$(srctree)/drivers/nand/inc -I$(srctree)/drivers/nand/include

obj-y += nand_api.o
obj-y += core/ jz_ctrl/  
#obj-y +=dma/
#obj-y += test/
#obj-y += vnand_test/
