ccflags-y += -Idrivers/video/jz4780-fb/
#obj-$(CONFIG_SLCD_SUSPEND_ALARM_WAKEUP_REFRESH) += lcd_suspend_update/
obj-y += slcd_update.o
obj-y += suspend_ops.o
obj-y += rtc_alarm.o

obj-y += customer_moduel_suspend_update_display/
