

obj-$(CONFIG_BOARD_4775_ORION)		+= orion/
obj-$(CONFIG_BOARD_4775_MENSA)		+= mensa/
obj-$(CONFIG_BOARD_4775_COMET)		+= comet/
obj-$(CONFIG_BOARD_4775_CONE)		+= cone/
obj-$(CONFIG_BOARD_4775_CONE_V1_2)	+= cone_v1_2/
