

obj-$(CONFIG_BOARD_PISCES)	+= pisces/
obj-$(CONFIG_BOARD_TEST)	+= test/
obj-$(CONFIG_BOARD_GIANT)	+= giant/
obj-$(CONFIG_BOARD_WARRIOR)	+= warrior/
obj-$(CONFIG_BOARD_HDMI_80)	+= hdmi-80/
obj-$(CONFIG_BOARD_M80)		+= m80/
obj-$(CONFIG_BOARD_M80701)		+= m80701/
obj-$(CONFIG_BOARD_NPM801)		+= npm801/
obj-$(CONFIG_BOARD_JI8070A)		+= ji8070a/
obj-$(CONFIG_BOARD_I88)			+= i88/
