

obj-$(CONFIG_BOARD_PISCES)	+= pisces/
obj-$(CONFIG_BOARD_TEST)	+= test/
obj-$(CONFIG_BOARD_GIANT)	+= giant/
obj-$(CONFIG_BOARD_WARRIOR)	+= warrior/
obj-$(CONFIG_BOARD_M80)		+= m80/
obj-$(CONFIG_BOARD_M80701)		+= m80701/
