
CFLAGS_KERNEL	+= -I$(srctree)/arch/mips/xburst/soc-m200/board/$(CONFIG_PRODUCT_NAME)/$(CONFIG_BOARD_NAME)

obj-$(CONFIG_PRODUCT_DEVELOP)		+= common/
obj-$(CONFIG_BOARD_DORADO_V20)		+= $(CONFIG_BOARD_NAME)/
